/**
 * Boss Dashboard: level/pillar constants and helpers used by the Insight Dashboard UI.
 * Insight text is generated by Claude via insightGenerator.ts and stored on the assessment.
 */

export type InsightPriorityPlaybook = { ref: string; name: string; status: 0 | 1 };

export const LEVEL_NAMES: Record<number, string> = {
  1: "Overwhelm",
  2: "Overworked",
  3: "Organised",
  4: "Overseer",
  5: "Owner",
};

export const PILLAR_KEYS = ["foundation", "vision", "velocity", "value"] as const;
export const PILLAR_NAMES: Record<(typeof PILLAR_KEYS)[number], string> = {
  foundation: "Owner Performance",
  vision: "Clarify Vision",
  velocity: "Control Velocity",
  value: "Create Value",
};

export const LEVEL_SUBTITLES: Record<number, string> = {
  1: "Survival mode. Doing everything yourself.",
  2: "Busy but inefficient. Working in the business.",
  3: "Systems emerging. Gaining clarity and control.",
  4: "Leading the team. Working on the business.",
  5: "True ownership. Business runs without you.",
};

export function getOverallLevel(score: number): { level: number; name: string } {
  if (score <= 20) return { level: 1, name: "Overwhelm" };
  if (score <= 40) return { level: 2, name: "Overworked" };
  if (score <= 60) return { level: 3, name: "Organised" };
  if (score <= 80) return { level: 4, name: "Overseer" };
  return { level: 5, name: "Owner" };
}
