import type { ProspectNextCall } from "./prospectNextCall";
import type { ProspectNextAction } from "./actionPlans/prospectFollowUp";
import type { ProspectStatusDisplay } from "./prospectStatus";

export type ProspectRow = {
  id: string;
  full_name: string;
  job_title: string | null;
  email: string | null;
  business_name: string | null;
  phone: string | null;
  type: string;
  prospect_status: string | null;
  status: ProspectStatusDisplay;
  coach_id?: string;
  coach_name?: string | null;
  coach_business_name?: string | null;
  last_score: number | null;
  last_completed_at: string | null;
  revenue: string | null;
  team_size: string | null;
  years_in_business: string | null;
  outcome: string | null;
  obstacles: string | null;
  preferred_support: string | null;
  boss_level: string | null;
  next_call?: ProspectNextCall | null;
  next_action?: ProspectNextAction | null;
  crm_contact_id?: string | null;
  crm_location_id?: string | null;
  created_at?: string | null;
};
