/** LeadRocks category slugs from Apify actor input schema. */

export type LeadrocksCategory = {
  slug: string;
  label: string;
};

export const LEADROCKS_CATEGORIES: LeadrocksCategory[] = [
  { slug: "accountants", label: "Accountants" },
  { slug: "acupuncture", label: "Acupuncture" },
  { slug: "airduct_cleaning", label: "Airduct Cleaning" },
  { slug: "angel_investor", label: "Angel Investor" },
  { slug: "architect_designer", label: "Architect Designer" },
  { slug: "audioligist", label: "Audiologist" },
  { slug: "author", label: "Author" },
  { slug: "auto_body_shops", label: "Auto Body Shops" },
  { slug: "auto_detailing", label: "Auto Detailing" },
  { slug: "barber", label: "Barber" },
  { slug: "book_keeping", label: "Book Keeping" },
  { slug: "business_coach", label: "Business Coach" },
  { slug: "cannabis", label: "Cannabis" },
  { slug: "ceo_marketing_us_11", label: "CEO Marketing US" },
  { slug: "chiropractor", label: "Chiropractor" },
  { slug: "client_lists", label: "Client Lists" },
  { slug: "clinic_director", label: "Clinic Director" },
  { slug: "commercial_cleaning", label: "Commercial Cleaning" },
  { slug: "construction", label: "Construction" },
  { slug: "consulting_management", label: "Consulting Management" },
  { slug: "cyber_security", label: "Cyber Security" },
  { slug: "dance_studio", label: "Dance Studio" },
  { slug: "dentist", label: "Dentist" },
  { slug: "dermatologist", label: "Dermatologist" },
  { slug: "dispensary", label: "Dispensary" },
  { slug: "ecommerce", label: "Ecommerce" },
  { slug: "event_manager", label: "Event Manager" },
  { slug: "event_planner", label: "Event Planner" },
  { slug: "fashion_brands", label: "Fashion Brands" },
  { slug: "fitness_coach", label: "Fitness Coach" },
  { slug: "flooring", label: "Flooring" },
  { slug: "food_brands", label: "Food Brands" },
  { slug: "georgia_agency_owners", label: "Georgia Agency Owners" },
  { slug: "gold_club", label: "Gold Club" },
  { slug: "grill", label: "Grill" },
  { slug: "gym_franchise", label: "Gym Franchise" },
  { slug: "gyms", label: "Gyms" },
  { slug: "healing_coach_melbourne", label: "Healing Coach Melbourne" },
  { slug: "health_care", label: "Health Care" },
  {
    slug: "health_care_ga_il_ok_al_ut_and_ka",
    label: "Health Care (GA/IL/OK/AL/UT/KA)",
  },
  {
    slug: "health_care_tn_oh_nv_kn_and_was",
    label: "Health Care (TN/OH/NV/KN/WA)",
  },
  { slug: "health_coach", label: "Health Coach" },
  { slug: "health_insurance", label: "Health Insurance" },
  { slug: "health_software", label: "Health Software" },
  { slug: "healthtech", label: "Healthtech" },
  { slug: "holistic_dentist", label: "Holistic Dentist" },
  { slug: "home_improvement_ontario", label: "Home Improvement Ontario" },
  { slug: "home_insurance_agent", label: "Home Insurance Agent" },
  { slug: "home_remodeling", label: "Home Remodeling" },
  { slug: "hospice_jay_osk", label: "Hospice" },
  { slug: "hvac", label: "HVAC" },
  { slug: "injury_attorney", label: "Injury Attorney" },
  { slug: "insurance_broker", label: "Insurance Broker" },
  { slug: "it_business", label: "IT Business" },
  { slug: "janitorial_services", label: "Janitorial Services" },
  { slug: "jewelry_stores", label: "Jewelry Stores" },
  { slug: "jewelry_stores_chicago", label: "Jewelry Stores Chicago" },
  { slug: "jewelry_stores_dc", label: "Jewelry Stores DC" },
  { slug: "law_firm", label: "Law Firm" },
  { slug: "law_firm_51_200e", label: "Law Firm (51–200 employees)" },
  { slug: "lawn_care", label: "Lawn Care" },
  { slug: "life_coach", label: "Life Coach" },
  { slug: "life_coaches", label: "Life Coaches" },
  { slug: "life_insurance", label: "Life Insurance" },
  {
    slug: "linkedin_search_list_1_marketing_ag",
    label: "LinkedIn Marketing List",
  },
  { slug: "logistic_broker", label: "Logistic Broker" },
  { slug: "manufacturing", label: "Manufacturing" },
  { slug: "marketing", label: "Marketing" },
  { slug: "marketing_agency", label: "Marketing Agency" },
  { slug: "marketing_us_1", label: "Marketing US" },
  { slug: "medical_practice", label: "Medical Practice" },
  { slug: "medspa", label: "Medspa" },
  { slug: "metal_company", label: "Metal Company" },
  { slug: "mortgage_broker", label: "Mortgage Broker" },
  { slug: "new_jersey_agency_owners", label: "New Jersey Agency Owners" },
  { slug: "nj_attorneys", label: "NJ Attorneys" },
  { slug: "non_profit", label: "Non Profit" },
  { slug: "non_profit_england", label: "Non Profit England" },
  { slug: "nurse_practitioner", label: "Nurse Practitioner" },
  { slug: "nurse_staffing_agency", label: "Nurse Staffing Agency" },
  { slug: "ohio_business_coaches", label: "Ohio Business Coaches" },
  { slug: "online_fitness_coach", label: "Online Fitness Coach" },
  { slug: "pain_management", label: "Pain Management" },
  { slug: "pediatric_dermatologist", label: "Pediatric Dermatologist" },
  { slug: "personal_assistant", label: "Personal Assistant" },
  { slug: "personal_injury", label: "Personal Injury" },
  { slug: "pest_control", label: "Pest Control" },
  { slug: "plastic_surgery", label: "Plastic Surgery" },
  { slug: "plumbing", label: "Plumbing" },
  { slug: "podcast", label: "Podcast" },
  { slug: "podcast_06", label: "Podcast 06" },
  { slug: "podcast_21", label: "Podcast 21" },
  { slug: "podcast_31", label: "Podcast 31" },
  { slug: "podcast_7", label: "Podcast 7" },
  { slug: "podcast_feb_1", label: "Podcast Feb 1" },
  { slug: "pool_cali", label: "Pool Cali" },
  { slug: "power_washing", label: "Power Washing" },
  { slug: "pr", label: "PR" },
  { slug: "pr_agency", label: "PR Agency" },
  { slug: "pressure_washing", label: "Pressure Washing" },
  { slug: "real_estate_agent", label: "Real Estate Agent" },
  { slug: "real_estate_developer", label: "Real Estate Developer" },
  { slug: "real_estate_investor", label: "Real Estate Investor" },
  { slug: "realtor", label: "Realtor" },
  { slug: "realtors", label: "Realtors" },
  { slug: "restaurant", label: "Restaurant" },
  { slug: "review", label: "Review" },
  { slug: "roofing", label: "Roofing" },
  { slug: "saas", label: "SaaS" },
  { slug: "sale_powur", label: "Sale Powur" },
  { slug: "seo", label: "SEO" },
  { slug: "software_devs", label: "Software Devs" },
  { slug: "solar", label: "Solar" },
  { slug: "staffing_agency", label: "Staffing Agency" },
  { slug: "stay_at_home_mom", label: "Stay At Home Mom" },
  {
    slug: "surveyor_self_employed_alex_f",
    label: "Surveyor Self Employed",
  },
  { slug: "texas_agency_owners", label: "Texas Agency Owners" },
  { slug: "travel_nurse", label: "Travel Nurse" },
  { slug: "trucking", label: "Trucking" },
  { slug: "wedding_photographer", label: "Wedding Photographer" },
  { slug: "window_cleaning", label: "Window Cleaning" },
  { slug: "wrap_shops", label: "Wrap Shops" },
  { slug: "yoga_studio", label: "Yoga Studio" },
];

export const LEADROCKS_US_STATES: Array<{ code: string; label: string }> = [
  { code: "AL", label: "Alabama" },
  { code: "AK", label: "Alaska" },
  { code: "AZ", label: "Arizona" },
  { code: "AR", label: "Arkansas" },
  { code: "CA", label: "California" },
  { code: "CO", label: "Colorado" },
  { code: "CT", label: "Connecticut" },
  { code: "DE", label: "Delaware" },
  { code: "FL", label: "Florida" },
  { code: "GA", label: "Georgia" },
  { code: "HI", label: "Hawaii" },
  { code: "ID", label: "Idaho" },
  { code: "IL", label: "Illinois" },
  { code: "IN", label: "Indiana" },
  { code: "IA", label: "Iowa" },
  { code: "KS", label: "Kansas" },
  { code: "KY", label: "Kentucky" },
  { code: "LA", label: "Louisiana" },
  { code: "ME", label: "Maine" },
  { code: "MD", label: "Maryland" },
  { code: "MA", label: "Massachusetts" },
  { code: "MI", label: "Michigan" },
  { code: "MN", label: "Minnesota" },
  { code: "MS", label: "Mississippi" },
  { code: "MO", label: "Missouri" },
  { code: "MT", label: "Montana" },
  { code: "NE", label: "Nebraska" },
  { code: "NV", label: "Nevada" },
  { code: "NH", label: "New Hampshire" },
  { code: "NJ", label: "New Jersey" },
  { code: "NM", label: "New Mexico" },
  { code: "NY", label: "New York" },
  { code: "NC", label: "North Carolina" },
  { code: "ND", label: "North Dakota" },
  { code: "OH", label: "Ohio" },
  { code: "OK", label: "Oklahoma" },
  { code: "OR", label: "Oregon" },
  { code: "PA", label: "Pennsylvania" },
  { code: "RI", label: "Rhode Island" },
  { code: "SC", label: "South Carolina" },
  { code: "SD", label: "South Dakota" },
  { code: "TN", label: "Tennessee" },
  { code: "TX", label: "Texas" },
  { code: "UT", label: "Utah" },
  { code: "VT", label: "Vermont" },
  { code: "VA", label: "Virginia" },
  { code: "WA", label: "Washington" },
  { code: "WV", label: "West Virginia" },
  { code: "WI", label: "Wisconsin" },
  { code: "WY", label: "Wyoming" },
];

/** Common team-size buckets seen in LeadRocks exports (cache / post-filter). */
export const LEADROCKS_TEAM_SIZES = [
  "Self-employed",
  "1-10",
  "11-50",
  "51-200",
  "201-500",
  "501-1000",
  "1001-5000",
  "5001-10000",
  "10001+",
] as const;

/** Revenue buckets aligned with LeadRocks CSV exports + local cache. */
export const LEADROCKS_REVENUE_RANGES = [
  "$0 - $1M",
  "$1M - $10M",
  "$10M - $50M",
  "$50M - $100M",
  "$100M+",
] as const;

/** Local UK MD/Founder/CEO/Owner corpus (CSV import — no Apify category needed). */
export const LOCAL_UK_OWNERS_CATEGORY_SLUG = "uk_business_owners";

/** Local US business-owner corpus (CSV import). */
export const LOCAL_US_OWNERS_CATEGORY_SLUG = "us_business_owners";

/**
 * LeadRocks export date for the current owners CSV batch (from filenames).
 * Migration / re-import also stamps each row; this is the UI fallback.
 */
export const LOCAL_UK_OWNERS_EXPORTED_AT = "2026-08-03";

export const LEADROCKS_JOB_TITLE_PRESETS = [
  "Owner",
  "Founder",
  "CEO",
  "Managing Director",
  "Director",
  "President",
  "Partner",
  "VP",
] as const;
