-- Classroom lesson consolidations (batch 2). Generated by scripts/generate-academy-consolidation-migration.mjs

-- Lead Gen Foundations
insert into public.academy_lesson_content (
  course_id,
  lesson_id,
  title,
  duration,
  body_markdown,
  video_chapters,
  updated_at
)
values (
  'get-calls',
  'get-calls-lead-generation-lead-gen-foundations',
  'Lead Gen Foundations',
  '',
  E'### What is this?\n\nHow lead generation works in the Profit Coach system — traffic, workflow, and why testing matters.\n\n### How to use this lesson\n\nWork through each step in the **Guide** tab in order.',
  jsonb_build_array(
    jsonb_build_object('id', 'traffic', 'title', 'Traffic: The Best Way to Get Leads', 'source_lesson_id', 'get-calls-lead-generation-intro-traffic-the-best-wat-to-get-leads'),
    jsonb_build_object('id', 'workflow', 'title', 'Lead Generation Workflow', 'source_lesson_id', 'get-calls-lead-generation-intro-lead-generation-workflow'),
    jsonb_build_object('id', 'testing', 'title', 'Testing Is Key To Lead Generation', 'source_lesson_id', 'get-calls-lead-generation-intro-testing-is-key-to-lead-generation')
  ),
  now()
)
on conflict (course_id, lesson_id) do update set
  title = excluded.title,
  duration = excluded.duration,
  body_markdown = excluded.body_markdown,
  video_chapters = excluded.video_chapters,
  updated_at = excluded.updated_at;

-- Run Your VIP Nurture
insert into public.academy_lesson_content (
  course_id,
  lesson_id,
  title,
  duration,
  body_markdown,
  video_chapters,
  updated_at
)
values (
  'get-calls',
  'get-calls-lead-generation-run-your-vip-nurture',
  'Run Your VIP Nurture',
  '',
  E'### What is this?\n\nBuild and run personalised VIP nurture for your top prospects before you scale outreach.\n\n### How to use this lesson\n\nWork through each step in the **Guide** tab in order.',
  jsonb_build_array(
    jsonb_build_object('id', 'overview', 'title', 'VIP Nurture Overview', 'source_lesson_id', 'get-calls-lead-generation-personalised-vip-nurture-top-100-vip-nurture-overview'),
    jsonb_build_object('id', 'top-100', 'title', 'How to Identify Your Top 100 Prospects', 'source_lesson_id', 'get-calls-lead-generation-personalised-vip-nurture-top-100-how-to-identify-your-top-100-prospects'),
    jsonb_build_object('id', 'messages', 'title', 'How To Craft Personalized Insightful Messages', 'source_lesson_id', 'get-calls-lead-generation-personalised-vip-nurture-top-100-how-to-craft-personalized-insightful-messages'),
    jsonb_build_object('id', 'channels', 'title', 'How To Use Multiple Channels To Engage', 'source_lesson_id', 'get-calls-lead-generation-personalised-vip-nurture-top-100-how-to-use-multiple-channels-to-engage')
  ),
  now()
)
on conflict (course_id, lesson_id) do update set
  title = excluded.title,
  duration = excluded.duration,
  body_markdown = excluded.body_markdown,
  video_chapters = excluded.video_chapters,
  updated_at = excluded.updated_at;

-- Set Up Connector Co-Pilot
insert into public.academy_lesson_content (
  course_id,
  lesson_id,
  title,
  duration,
  body_markdown,
  video_chapters,
  updated_at
)
values (
  'get-calls',
  'get-calls-replying-to-leads-set-up-connector-co-pilot',
  'Set Up Connector Co-Pilot',
  '',
  E'### What is this?\n\nConfigure Connector AI Co-Pilot (or Auto-Pilot) to help you reply to prospects.\n\n### How to use this lesson\n\nWork through each step in the **Guide** tab in order.',
  jsonb_build_array(
    jsonb_build_object('id', 'setup', 'title', 'How to Set Up Connector Ai Co-Pilot', 'source_lesson_id', 'get-calls-replying-to-leads-how-to-set-up-connector-ai-co-pilot'),
    jsonb_build_object('id', 'mode', 'title', 'Choosing between Ai Co-Pilot & Auto-Pilot', 'source_lesson_id', 'get-calls-replying-to-leads-choosing-between-ai-co-pilot-auto-pilot'),
    jsonb_build_object('id', 'activate', 'title', 'How to Activate The Ai and Test', 'source_lesson_id', 'get-calls-replying-to-leads-how-to-activate-the-ai-and-test')
  ),
  now()
)
on conflict (course_id, lesson_id) do update set
  title = excluded.title,
  duration = excluded.duration,
  body_markdown = excluded.body_markdown,
  video_chapters = excluded.video_chapters,
  updated_at = excluded.updated_at;

-- Get Started With Connector
insert into public.academy_lesson_content (
  course_id,
  lesson_id,
  title,
  duration,
  body_markdown,
  video_chapters,
  updated_at
)
values (
  'get-calls',
  'get-calls-lead-generation-get-started-with-connector',
  'Get Started With Connector',
  '',
  E'### What is this?\n\nRegister for Connector and prepare your connection and follow-up messages.\n\n### How to use this lesson\n\nWork through each step in the **Guide** tab in order.',
  jsonb_build_array(
    jsonb_build_object('id', 'register', 'title', 'What is Connector & How To Register for Connector Ai', 'source_lesson_id', 'get-calls-lead-generation-ai-automation-what-is-connector-how-to-register-for-connector-ai'),
    jsonb_build_object('id', 'overview', 'title', 'Connector Campaign: Overview', 'source_lesson_id', 'get-calls-lead-generation-ai-automation-connector-campaign-overview'),
    jsonb_build_object('id', 'connection-message', 'title', 'Write A LinkedIn Connection Message', 'source_lesson_id', 'get-calls-lead-generation-ai-automation-write-a-linkedin-connection-message'),
    jsonb_build_object('id', 'follow-up-templates', 'title', 'Connector Campaign: Editing Follow-up Message Templates', 'source_lesson_id', 'get-calls-lead-generation-ai-automation-connector-campaign-editing-follow-up-message-templates')
  ),
  now()
)
on conflict (course_id, lesson_id) do update set
  title = excluded.title,
  duration = excluded.duration,
  body_markdown = excluded.body_markdown,
  video_chapters = excluded.video_chapters,
  updated_at = excluded.updated_at;

-- Launch Your Connector Campaign
insert into public.academy_lesson_content (
  course_id,
  lesson_id,
  title,
  duration,
  body_markdown,
  video_chapters,
  updated_at
)
values (
  'get-calls',
  'get-calls-lead-generation-launch-your-connector-campaign',
  'Launch Your Connector Campaign',
  '6m',
  E'### What is this?\n\nCreate and launch your Connector campaigns — including open InMail when needed.\n\n### How to use this lesson\n\nWork through each step in the **Guide** tab in order.',
  jsonb_build_array(
    jsonb_build_object('id', 'create-campaign', 'title', 'How to Create Campaigns in Connect Ai', 'source_lesson_id', 'get-calls-lead-generation-ai-automation-how-to-create-campaigns-in-connect-ai'),
    jsonb_build_object('id', 'connected-campaign', 'title', 'How to Create a Campaign for Prospects you are Already Connected With', 'source_lesson_id', 'get-calls-lead-generation-ai-automation-how-to-create-a-campaign-for-prospects-you-are-already-connected-with'),
    jsonb_build_object('id', 'open-inmail', 'title', 'Targeted Open InMail: Craft Open InMail Message', 'source_lesson_id', 'get-calls-lead-generation-ai-automation-targeted-open-inmail-craft-open-inmail-message', 'duration', '6m')
  ),
  now()
)
on conflict (course_id, lesson_id) do update set
  title = excluded.title,
  duration = excluded.duration,
  body_markdown = excluded.body_markdown,
  video_chapters = excluded.video_chapters,
  updated_at = excluded.updated_at;

-- Design Your Coaching Offer
insert into public.academy_lesson_content (
  course_id,
  lesson_id,
  title,
  duration,
  body_markdown,
  video_chapters,
  updated_at
)
values (
  'win-clients',
  'win-clients-design-your-coaching-offer',
  'Design Your Coaching Offer',
  '50m',
  E'### What is this?\n\nClarify what clients are really buying, structure your offer, and set pricing.\n\n### How to use this lesson\n\nWatch straight through or jump between chapters on the timeline.',
  jsonb_build_array(
    jsonb_build_object('id', 'the-gap', 'title', 'The Gap: What Clients Are Really Buying', 'source_lesson_id', 'coach-action-plan-building-a-world-class-coaching-practice-57m-what-are-people-actually-buying-the-gap', 'duration', '19m'),
    jsonb_build_object('id', 'structure', 'title', 'How To Structure Your Coaching Offer', 'source_lesson_id', 'coach-action-plan-building-a-world-class-coaching-practice-57m-structuring-your-coaching-offer-what-are-you-actually-selling', 'duration', '11m'),
    jsonb_build_object('id', 'pricing', 'title', 'Pricing & Payment Options', 'source_lesson_id', 'coach-action-plan-building-a-world-class-coaching-practice-57m-pricing-setting-the-right-packages-investment-for-your-coaching', 'duration', '20m')
  ),
  now()
)
on conflict (course_id, lesson_id) do update set
  title = excluded.title,
  duration = excluded.duration,
  body_markdown = excluded.body_markdown,
  video_chapters = excluded.video_chapters,
  updated_at = excluded.updated_at;

-- Deliver Your Sales Pitch
insert into public.academy_lesson_content (
  course_id,
  lesson_id,
  title,
  duration,
  body_markdown,
  video_chapters,
  updated_at
)
values (
  'win-clients',
  'win-clients-deliver-your-sales-pitch',
  'Deliver Your Sales Pitch',
  '63m',
  E'### What is this?\n\nRun the pitch section of your sales call — from principles through delivery.\n\n### How to use this lesson\n\nStart with the overview in the **Guide** tab, then watch through or scrub between chapters.',
  jsonb_build_array(
    jsonb_build_object('id', 'overview', 'title', 'Sales Pitch Overview', 'source_lesson_id', 'win-clients-sales-pitch-sales-pitch-overview'),
    jsonb_build_object('id', 'principles', 'title', 'Sales Call: Pitching Principles', 'source_lesson_id', 'win-clients-sales-pitch-sales-call-pitching-principles', 'duration', '6m'),
    jsonb_build_object('id', 'transition', 'title', 'Sales Call: Transition Into Pitch', 'source_lesson_id', 'win-clients-sales-pitch-sales-call-transition-into-pitch', 'duration', '3m'),
    jsonb_build_object('id', 'the-pitch', 'title', 'Sales Call: The Pitch', 'source_lesson_id', 'win-clients-sales-pitch-sales-call-the-pitch', 'duration', '34m'),
    jsonb_build_object('id', 'questions-in-pitch', 'title', 'Sales Call: Asking Questions In The Pitch', 'source_lesson_id', 'win-clients-sales-pitch-sales-call-asking-questions-in-the-pitch', 'duration', '3m'),
    jsonb_build_object('id', 'demo', 'title', 'Sales Pitch Demo: Perfecting Your Pitch Performance', 'source_lesson_id', 'win-clients-sales-pitch-sales-pitch-demo-perfecting-your-pitch-performance', 'duration', '8m'),
    jsonb_build_object('id', 'share-slides', 'title', 'How To Share Slides On A Sales Call', 'source_lesson_id', 'win-clients-sales-pitch-how-to-share-slides-on-a-sales-call-so-they-don-t-see-your-script', 'duration', '9m')
  ),
  now()
)
on conflict (course_id, lesson_id) do update set
  title = excluded.title,
  duration = excluded.duration,
  body_markdown = excluded.body_markdown,
  video_chapters = excluded.video_chapters,
  updated_at = excluded.updated_at;

-- Post-Pitch, Price & Close
insert into public.academy_lesson_content (
  course_id,
  lesson_id,
  title,
  duration,
  body_markdown,
  video_chapters,
  updated_at
)
values (
  'win-clients',
  'win-clients-post-pitch-price-and-close',
  'Post-Pitch, Price & Close',
  '119m',
  E'### What is this?\n\nHandle questions after the pitch, present price, and move toward the close.\n\n### How to use this lesson\n\nWatch straight through or jump between chapters on the timeline.',
  jsonb_build_array(
    jsonb_build_object('id', 'check-questions', 'title', 'Sales Call: Post Pitch - Checking For Questions', 'source_lesson_id', 'win-clients-sales-pitch-sales-call-post-pitch-checking-for-questions', 'duration', '7m'),
    jsonb_build_object('id', 'answer-framework', 'title', 'Sales Call: Post Pitch - Framework For Answering Questions', 'source_lesson_id', 'win-clients-sales-pitch-sales-call-post-pitch-framework-for-answering-questions', 'duration', '6m'),
    jsonb_build_object('id', 'post-pitch-process', 'title', 'Post Pitch Process', 'source_lesson_id', 'win-clients-sales-pitch-post-pitch-process', 'duration', '69m'),
    jsonb_build_object('id', 'price-pitch', 'title', 'Price Pitch', 'source_lesson_id', 'win-clients-sales-pitch-price-pitch', 'duration', '35m'),
    jsonb_build_object('id', 'when-price', 'title', 'When Should You Discuss Price', 'source_lesson_id', 'win-clients-sales-pitch-sales-process-questions-when-should-you-discuss-price', 'duration', '2m')
  ),
  now()
)
on conflict (course_id, lesson_id) do update set
  title = excluded.title,
  duration = excluded.duration,
  body_markdown = excluded.body_markdown,
  video_chapters = excluded.video_chapters,
  updated_at = excluded.updated_at;

-- Onboard a New Client: Sessions 1–4
insert into public.academy_lesson_content (
  course_id,
  lesson_id,
  title,
  duration,
  body_markdown,
  video_chapters,
  updated_at
)
values (
  'coach-clients',
  'coach-clients-onboard-a-new-client-sessions-1-4',
  'Onboard a New Client: Sessions 1–4',
  '99m',
  E'### What is this?\n\nYour first four client sessions — setup through ninety-day plan.\n\n### How to use this lesson\n\nWatch in order or jump to the session you are preparing for.',
  jsonb_build_array(
    jsonb_build_object('id', 'setup', 'title', 'How To Setup A New Client', 'source_lesson_id', 'coach-clients-client-onboarding-how-to-setup-a-new-client', 'duration', '2m'),
    jsonb_build_object('id', 'session-1', 'title', 'Session 1: Profit Systems & Dashboard', 'source_lesson_id', 'coach-clients-client-onboarding-session-1-profit-systems-dashboard', 'duration', '32m'),
    jsonb_build_object('id', 'session-2', 'title', 'Session 2: Leverage & Critical Issues', 'source_lesson_id', 'coach-clients-client-onboarding-session-2-leverage-critical-issues', 'duration', '18m'),
    jsonb_build_object('id', 'session-3', 'title', 'Session 3: Align 3-Year Plan', 'source_lesson_id', 'coach-clients-client-onboarding-session-3-align-3-year-plan', 'duration', '23m'),
    jsonb_build_object('id', 'session-4', 'title', 'Session 4: Ninety Day Plan', 'source_lesson_id', 'coach-clients-client-onboarding-session-4-ninety-day-plan', 'duration', '24m')
  ),
  now()
)
on conflict (course_id, lesson_id) do update set
  title = excluded.title,
  duration = excluded.duration,
  body_markdown = excluded.body_markdown,
  video_chapters = excluded.video_chapters,
  updated_at = excluded.updated_at;

-- Start & End a Coaching Session
insert into public.academy_lesson_content (
  course_id,
  lesson_id,
  title,
  duration,
  body_markdown,
  video_chapters,
  updated_at
)
values (
  'coach-clients',
  'coach-clients-start-and-end-a-coaching-session',
  'Start & End a Coaching Session',
  '',
  E'### What is this?\n\nHow to open and close a coaching session with clarity and momentum.\n\n### How to use this lesson\n\nWork through both steps in the **Guide** tab.',
  jsonb_build_array(
    jsonb_build_object('id', 'start', 'title', 'How To Start A Coaching Session', 'source_lesson_id', 'coach-clients-coachiing-session-structure-how-to-start-a-coaching-session'),
    jsonb_build_object('id', 'end', 'title', 'How To End A Coaching Session', 'source_lesson_id', 'coach-clients-coachiing-session-structure-how-eo-end-a-coaching-session')
  ),
  now()
)
on conflict (course_id, lesson_id) do update set
  title = excluded.title,
  duration = excluded.duration,
  body_markdown = excluded.body_markdown,
  video_chapters = excluded.video_chapters,
  updated_at = excluded.updated_at;

-- Welcome to Profit Coach Certification
insert into public.academy_lesson_content (
  course_id,
  lesson_id,
  title,
  duration,
  body_markdown,
  video_chapters,
  updated_at
)
values (
  'coach-clients',
  'coach-clients-certification-welcome-to-profit-coach-certification',
  'Welcome to Profit Coach Certification',
  '',
  E'### What is this?\n\nEverything you need before Week 1 — orientation, faculty, workbook, and ROI tools.\n\n### How to use this lesson\n\nWork through each step in the **Guide** tab before starting Coaching Foundations.',
  jsonb_build_array(
    jsonb_build_object('id', 'welcome', 'title', 'Welcome To Your Coaching Transformation', 'source_lesson_id', 'coach-clients-certification-welcome-to-the-profit-coach-certification-welcome-to-your-coaching-transformation'),
    jsonb_build_object('id', 'maximise', 'title', 'How to Maximise Your Certification Experience', 'source_lesson_id', 'coach-clients-certification-welcome-to-the-profit-coach-certification-how-to-maximise-your-certification-experience'),
    jsonb_build_object('id', 'faculty', 'title', 'Meet Your Faculty & Our Coaching Philosophy', 'source_lesson_id', 'coach-clients-certification-welcome-to-the-profit-coach-certification-meet-your-faculty-our-coaching-philosophy'),
    jsonb_build_object('id', 'roi-calculator', 'title', 'Profit Coach ROI Calculator', 'source_lesson_id', 'coach-clients-certification-welcome-to-the-profit-coach-certification-profit-coacbh-roi-calculator'),
    jsonb_build_object('id', 'workbook', 'title', 'Profit Coach Certification Workbook', 'source_lesson_id', 'coach-clients-certification-welcome-to-the-profit-coach-certification-profit-coach-certification-workbook')
  ),
  now()
)
on conflict (course_id, lesson_id) do update set
  title = excluded.title,
  duration = excluded.duration,
  body_markdown = excluded.body_markdown,
  video_chapters = excluded.video_chapters,
  updated_at = excluded.updated_at;

-- Certification Week 1: COACH Foundations
insert into public.academy_lesson_content (
  course_id,
  lesson_id,
  title,
  duration,
  body_markdown,
  video_chapters,
  updated_at
)
values (
  'coach-clients',
  'coach-clients-certification-week-1-coach-foundations',
  'Certification Week 1: COACH Foundations',
  '108m',
  E'### What is this?\n\nWeek 1 of certification — coaching fundamentals and the COACH Method.\n\n### How to use this lesson\n\nWatch in order; complete the Week 1 quiz in the **Guide** tab when finished.',
  jsonb_build_array(
    jsonb_build_object('id', 'what-is-coaching', 'title', 'What is Coaching', 'source_lesson_id', 'coach-clients-certification-coaching-foundations-what-is-coaching', 'duration', '8m'),
    jsonb_build_object('id', 'coaching-style', 'title', 'What is your coaching style?', 'source_lesson_id', 'coach-action-plan-building-a-world-class-coaching-practice-57m-what-is-your-coaching-style-3-traits-that-define-how-you-coach'),
    jsonb_build_object('id', 'feedback', 'title', 'The Power of Effective Feedback', 'source_lesson_id', 'coach-clients-certification-coaching-foundations-the-power-of-effective-feedback', 'duration', '11m'),
    jsonb_build_object('id', 'use-it-or-lose-it', 'title', 'The Use It or Lose It Principle', 'source_lesson_id', 'coach-clients-certification-coaching-foundations-the-use-it-or-lose-it-principle', 'duration', '8m'),
    jsonb_build_object('id', 'active-listening', 'title', 'Core Skill: Active Listening + Demo', 'source_lesson_id', 'coach-clients-certification-coaching-foundations-core-skill-active-listening-demo', 'duration', '12m'),
    jsonb_build_object('id', 'coach-overview', 'title', 'The COACH Method Overview', 'source_lesson_id', 'coach-clients-certification-coaching-foundations-the-coach-method-overview', 'duration', '4m'),
    jsonb_build_object('id', 'using-coach', 'title', 'Using the COACH Method', 'source_lesson_id', 'coach-clients-certification-coaching-foundations-using-the-coach-method', 'duration', '23m'),
    jsonb_build_object('id', 'coaching-cube', 'title', 'The Coaching Cube', 'source_lesson_id', 'coach-clients-certification-coaching-foundations-the-coaching-cube', 'duration', '3m'),
    jsonb_build_object('id', 'simulator', 'title', 'Client Simulator: Coach Practice', 'source_lesson_id', 'coach-clients-certification-coaching-foundations-client-simulator-coach-practice', 'duration', '7m'),
    jsonb_build_object('id', 'live-demo', 'title', 'Live Coaching Session Demo', 'source_lesson_id', 'coach-clients-certification-coaching-foundations-live-coaching-session-demo', 'duration', '14m'),
    jsonb_build_object('id', 'ideal-structure', 'title', 'Ideal Session Structure', 'source_lesson_id', 'coach-clients-certification-coaching-foundations-ideal-session-structure', 'duration', '8m'),
    jsonb_build_object('id', 'more-sessions', 'title', 'How COACH Creates More Sessions', 'source_lesson_id', 'coach-clients-certification-coaching-foundations-how-coach-creates-more-sessions', 'duration', '2m'),
    jsonb_build_object('id', 'review', 'title', 'Coach Foundations Review', 'source_lesson_id', 'coach-clients-certification-coaching-foundations-coach-foundations-review', 'duration', '8m'),
    jsonb_build_object('id', 'week-1-quiz', 'title', 'Week 1 Quiz - Introduction and COACH', 'source_lesson_id', 'coach-clients-certification-coaching-foundations-week-1-quiz-introduction-and-coach')
  ),
  now()
)
on conflict (course_id, lesson_id) do update set
  title = excluded.title,
  duration = excluded.duration,
  body_markdown = excluded.body_markdown,
  video_chapters = excluded.video_chapters,
  updated_at = excluded.updated_at;

-- Certification Week 2: Powerful Questions
insert into public.academy_lesson_content (
  course_id,
  lesson_id,
  title,
  duration,
  body_markdown,
  video_chapters,
  updated_at
)
values (
  'coach-clients',
  'coach-clients-certification-week-2-powerful-questions',
  'Certification Week 2: Powerful Questions',
  '72m',
  E'### What is this?\n\nWeek 2 — the POWER framework and powerful questioning.\n\n### How to use this lesson\n\nWatch in order; complete assessments and quizzes in the **Guide** tab.',
  jsonb_build_array(
    jsonb_build_object('id', 'icf', 'title', 'ICF 8 Core Competencies', 'source_lesson_id', 'coach-clients-certification-the-exact-questions-to-ask-clients-icf-8-core-competencies', 'duration', '17m'),
    jsonb_build_object('id', 'power-overview', 'title', 'The POWER Framework Overview', 'source_lesson_id', 'coach-clients-certification-the-exact-questions-to-ask-clients-the-power-framework-overview', 'duration', '4m'),
    jsonb_build_object('id', 'exercises', 'title', 'How To Ask Powerful Questions + Exercises', 'source_lesson_id', 'coach-clients-certification-the-exact-questions-to-ask-clients-how-to-ask-powerful-questions-exercises', 'duration', '15m'),
    jsonb_build_object('id', 'powerful-vs-transformational', 'title', 'Powerful Vs Transformational Questions', 'source_lesson_id', 'coach-clients-certification-the-exact-questions-to-ask-clients-powerful-vs-transformational-questions', 'duration', '14m'),
    jsonb_build_object('id', 'comm-assessment', 'title', 'Communication Skills Assessment', 'source_lesson_id', 'coach-clients-certification-the-exact-questions-to-ask-clients-communication-skills-assessment'),
    jsonb_build_object('id', 'power-detail', 'title', 'The POWER Framework Detail', 'source_lesson_id', 'coach-clients-certification-the-exact-questions-to-ask-clients-the-power-framework-detail', 'duration', '11m'),
    jsonb_build_object('id', 'week-2-review', 'title', 'Week 2: Coach Superpowers Review', 'source_lesson_id', 'coach-clients-certification-the-exact-questions-to-ask-clients-week-2-coach-superpowers-review', 'duration', '9m'),
    jsonb_build_object('id', 'simulator', 'title', 'Client Simulator: Profitability Issues', 'source_lesson_id', 'coach-clients-certification-the-exact-questions-to-ask-clients-client-simullator-profitabilty-issues-management-consultant', 'duration', '2m'),
    jsonb_build_object('id', 'great-coach-quiz', 'title', 'Becoming A Great Coach Quiz', 'source_lesson_id', 'coach-clients-certification-the-exact-questions-to-ask-clients-becoming-a-great-coach-quiz'),
    jsonb_build_object('id', 'superpowers-quiz', 'title', 'SuperPOWERs Quiz', 'source_lesson_id', 'coach-clients-certification-the-exact-questions-to-ask-clients-superpowers-quiz'),
    jsonb_build_object('id', 'questioning-quiz', 'title', 'Questioning and Listening Quiz', 'source_lesson_id', 'coach-clients-certification-the-exact-questions-to-ask-clients-questioning-and-listening-quiz')
  ),
  now()
)
on conflict (course_id, lesson_id) do update set
  title = excluded.title,
  duration = excluded.duration,
  body_markdown = excluded.body_markdown,
  video_chapters = excluded.video_chapters,
  updated_at = excluded.updated_at;

-- Certification Week 3: Lasting Transformation
insert into public.academy_lesson_content (
  course_id,
  lesson_id,
  title,
  duration,
  body_markdown,
  video_chapters,
  updated_at
)
values (
  'coach-clients',
  'coach-clients-certification-week-3-lasting-transformation',
  'Certification Week 3: Lasting Transformation',
  '130m',
  E'### What is this?\n\nWeek 3 — sustainable transformation, mindset, and advanced coaching skills.\n\n### How to use this lesson\n\nWatch in order; complete the mindset quiz in the **Guide** tab.',
  jsonb_build_array(
    jsonb_build_object('id', 'overview', 'title', 'Sprint Week 3 Overview', 'source_lesson_id', 'coach-clients-certification-create-lasting-transformation-sprint-week-3-overview', 'duration', '7m'),
    jsonb_build_object('id', 'sustainable', 'title', 'Creating Sustainable Transformation', 'source_lesson_id', 'coach-clients-certification-create-lasting-transformation-creating-sustainable-transformation', 'duration', '13m'),
    jsonb_build_object('id', 'add-value', 'title', 'How To Continually Add Value', 'source_lesson_id', 'coach-clients-certification-create-lasting-transformation-how-to-continually-add-value', 'duration', '18m'),
    jsonb_build_object('id', 'mindset', 'title', 'Coaching Mindset', 'source_lesson_id', 'coach-clients-certification-create-lasting-transformation-coaching-mindset', 'duration', '13m'),
    jsonb_build_object('id', 'state-of-mind', 'title', 'Controlling Your State Of Mind', 'source_lesson_id', 'coach-clients-certification-create-lasting-transformation-controlling-your-state-of-mind', 'duration', '22m'),
    jsonb_build_object('id', 'psychology', 'title', 'How Psychology Affects Mindset', 'source_lesson_id', 'coach-clients-certification-create-lasting-transformation-how-psychology-affects-mindset', 'duration', '7m'),
    jsonb_build_object('id', 'vocabulary', 'title', 'Use Vocabulary to Change Perception', 'source_lesson_id', 'coach-clients-certification-create-lasting-transformation-use-vocabulary-to-change-perception', 'duration', '6m'),
    jsonb_build_object('id', 'mindset-quiz', 'title', 'Coaching Mindset Quiz', 'source_lesson_id', 'coach-clients-certification-create-lasting-transformation-coaching-mindset-quiz'),
    jsonb_build_object('id', 'coaching-sheet', 'title', 'How To Use The Coaching Sheet In Sessions', 'source_lesson_id', 'coach-clients-certification-create-lasting-transformation-how-to-use-the-coaching-sheet-in-sessions', 'duration', '9m'),
    jsonb_build_object('id', 'feedback-review', 'title', 'Coaching a Person Feedback Review', 'source_lesson_id', 'coach-clients-certification-create-lasting-transformation-coachin-a-person-feedback-review', 'duration', '9m'),
    jsonb_build_object('id', 'ai-vs-person', 'title', 'Pros & Cons Coaching AI vs Person', 'source_lesson_id', 'coach-clients-certification-create-lasting-transformation-pros-cons-coachin-ai-vs-person', 'duration', '15m'),
    jsonb_build_object('id', 'advanced-selling', 'title', 'Advanced Coaching Skills & Selling', 'source_lesson_id', 'coach-clients-certification-create-lasting-transformation-advanced-coaching-skills-selling', 'duration', '5m'),
    jsonb_build_object('id', 'homework', 'title', 'Sprint Week 3 Review + Homework', 'source_lesson_id', 'coach-clients-certification-create-lasting-transformation-sprint-week-3-review-homework', 'duration', '6m')
  ),
  now()
)
on conflict (course_id, lesson_id) do update set
  title = excluded.title,
  duration = excluded.duration,
  body_markdown = excluded.body_markdown,
  video_chapters = excluded.video_chapters,
  updated_at = excluded.updated_at;

-- Certification Week 4: World-Class Coach
insert into public.academy_lesson_content (
  course_id,
  lesson_id,
  title,
  duration,
  body_markdown,
  video_chapters,
  updated_at
)
values (
  'coach-clients',
  'coach-clients-certification-week-4-world-class-coach',
  'Certification Week 4: World-Class Coach',
  '114m',
  E'### What is this?\n\nWeek 4 — leadership coaching, ethics, tools, certification assessment, and next steps.\n\n### How to use this lesson\n\nWatch in order; complete quizzes and the certification assessment in the **Guide** tab.',
  jsonb_build_array(
    jsonb_build_object('id', 'coaching-as-leader', 'title', 'Coaching As A Leader', 'source_lesson_id', 'coach-clients-certification-becoming-a-world-class-business-coach-coaching-as-a-leader', 'duration', '23m'),
    jsonb_build_object('id', 'leader-quiz', 'title', 'Coaching As A Leader Quiz', 'source_lesson_id', 'coach-clients-certification-becoming-a-world-class-business-coach-coaching-as-a-leader-quiz'),
    jsonb_build_object('id', 'ethics', 'title', 'Ethical Dilemmas and difficult situations', 'source_lesson_id', 'coach-clients-certification-becoming-a-world-class-business-coach-ethical-dilemmas-and-difficult-situations', 'duration', '14m'),
    jsonb_build_object('id', 'ethics-quiz', 'title', 'Ethical Dilemas Quiz', 'source_lesson_id', 'coach-clients-certification-becoming-a-world-class-business-coach-ethical-dilemas-quiz'),
    jsonb_build_object('id', 'using-tools', 'title', 'Client Sessions & Using Tools', 'source_lesson_id', 'coach-clients-certification-becoming-a-world-class-business-coach-client-sessions-using-tools', 'duration', '20m'),
    jsonb_build_object('id', 'tools-example', 'title', 'Example Using tools & COACH Method', 'source_lesson_id', 'coach-clients-certification-becoming-a-world-class-business-coach-example-using-tools-coach-method', 'duration', '7m'),
    jsonb_build_object('id', 'master-selling', 'title', 'Master COACH to Master Selling', 'source_lesson_id', 'coach-clients-certification-becoming-a-world-class-business-coach-master-coach-to-master-selling', 'duration', '12m'),
    jsonb_build_object('id', 'assessment', 'title', 'Business Coach Certification Assessment', 'source_lesson_id', 'coach-clients-certification-becoming-a-world-class-business-coach-business-coach-certification-assessment', 'duration', '8m'),
    jsonb_build_object('id', 'feedback-survey', 'title', 'Certification Feedback Survey', 'source_lesson_id', 'coach-clients-certification-becoming-a-world-class-business-coach-certification-feedback-survey', 'duration', '11m'),
    jsonb_build_object('id', 'round-up', 'title', 'Certification Round-up & Next Steps', 'source_lesson_id', 'coach-clients-certification-becoming-a-world-class-business-coach-certificaiton-round-up-next-steps', 'duration', '6m'),
    jsonb_build_object('id', 'blueprint', 'title', 'Business Blueprint', 'source_lesson_id', 'coach-clients-certification-becoming-a-world-class-business-coach-business-blueprint', 'duration', '13m')
  ),
  now()
)
on conflict (course_id, lesson_id) do update set
  title = excluded.title,
  duration = excluded.duration,
  body_markdown = excluded.body_markdown,
  video_chapters = excluded.video_chapters,
  updated_at = excluded.updated_at;

