-- Narrow the shared All coaches view to join / activity / LinkedIn / billing columns.
update public.admin_coach_table_views
set
  settings = jsonb_set(
    jsonb_set(
      settings,
      '{columnVisibility}',
      '{
        "slug": false,
        "email": false,
        "joinDate": true,
        "goalLevel": false,
        "clients": false,
        "linkedinProfile": true,
        "directory": false,
        "certification": false,
        "conference": false,
        "currentLevel": false,
        "goalBy": false,
        "lastLogin": false,
        "lastActive": true,
        "crm": false,
        "salesRobot": false,
        "activeCampaigns": false,
        "payingAccounts": false,
        "profitCoachEmail": false,
        "accessTier": true,
        "recurringPayment": true,
        "recurringActive": true,
        "payments": true,
        "calendarEmbed": false,
        "leadWebhook": false,
        "communityBio": false,
        "directorySummary": false,
        "directoryBio": false,
        "landing": false
      }'::jsonb,
      true
    ),
    '{columnOrder}',
    '[
      "joinDate",
      "lastActive",
      "linkedinProfile",
      "accessTier",
      "recurringPayment",
      "recurringActive",
      "payments",
      "slug",
      "email",
      "clients",
      "conference",
      "lastLogin",
      "goalLevel",
      "currentLevel",
      "goalBy",
      "directory",
      "certification",
      "communityBio",
      "directorySummary",
      "directoryBio",
      "crm",
      "calendarEmbed",
      "leadWebhook",
      "salesRobot",
      "activeCampaigns",
      "payingAccounts",
      "profitCoachEmail",
      "landing"
    ]'::jsonb,
    true
  ),
  updated_at = now()
where lower(trim(name)) in ('all', 'all coaches');
