import fs from "node:fs";
import { createClient } from "@supabase/supabase-js";
import { chromium } from "playwright";
const env = Object.fromEntries(fs.readFileSync(".env.local", "utf8").split("\n").filter((l) => l.includes("=") && !l.trim().startsWith("#")).map((l) => { const i = l.indexOf("="); return [l.slice(0, i).trim(), l.slice(i + 1).trim().replace(/^["']|["']$/g, "")]; }));
const ref = env.NEXT_PUBLIC_SUPABASE_URL.match(/https:\/\/([^.]+)\./)[1];
const admin = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false } });
const anon = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.NEXT_PUBLIC_SUPABASE_ANON_KEY, { auth: { persistSession: false } });
const { data: u } = await admin.auth.admin.getUserById("01df174c-646c-4a29-8e76-9d0132735434");
const { data: link } = await admin.auth.admin.generateLink({ type: "magiclink", email: u.user.email });
const { data: ses } = await anon.auth.verifyOtp({ token_hash: link.properties.hashed_token, type: "magiclink" });
const out = process.argv[2];
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 } });
await ctx.addInitScript(([k, v]) => { localStorage.setItem(k, v); sessionStorage.setItem("blueprint-preview-coach", "5cb89c87-88a9-4cfc-9f95-9591f74f8529"); localStorage.setItem("practice-assistant-open", "0"); }, [`sb-${ref}-auth-token`, JSON.stringify(ses.session)]);
const page = await ctx.newPage();
await page.goto("http://localhost:3002/admin/blueprint/coach/blueprint", { waitUntil: "networkidle", timeout: 180000 });
await page.waitForTimeout(3000);
await page.setViewportSize({ width: 794, height: 1123 });
await page.emulateMedia({ media: "print" });
await page.waitForTimeout(800);
await page.screenshot({ path: out + "-p1.png" });
await page.evaluate(() => document.getElementById("c-2")?.scrollIntoView());
await page.waitForTimeout(500);
await page.screenshot({ path: out + "-p2.png" });
const h = await page.evaluate(() => document.documentElement.scrollHeight);
console.log("print height", h);
await browser.close();
